### ISSUE TITLE
News item not displaying in feedfolder

### ISSUE THREAD

**Issue by richardtc** [collective/Products.feedfeeder#15]
Products.feedfeeder = 3.0.1

After adding a news item into feedfolder in Plone, which is saved (I can  see it listed in the ZMI's FeedfeederFolder),  I'm unable to see the item after clicking on the Contents icon (in left column). Instead, the feedfolder displays a circle which rotates without stopping and I can see the following error in the terminal. Also, the new item does not appear in the feedfolder view. Note that items input from RSS feeds work fine.

2016-10-14 17:47:25 ERROR Zope.SiteErrorLog 1476442045.790.107013713297 http://192.168.43.34:17470/plonesite/@@getVocabulary
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.app.content.browser.vocabulary, line 241, in **call**
  Module plone.app.content.utils, line 16, in json_dumps
  Module json, line 251, in dumps
  Module json.encoder, line 207, in encode
  Module json.encoder, line 270, in iterencode
ValueError: Circular reference detected

```
Plone 5.0.6 (5016)
CMF 2.2.10
Zope 2.13.24
Python 2.7.12 (default, Oct 12 2016, 13:45:40) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
PIL 3.3.0 (Pillow)
```

**Comment by mauritsvanrees** [comment]
That is a strange bug.  Ah, but I see someone has already fixed it: https://github.com/plone/plone.app.content/pull/104
The fix is included since plone.app.content 3.3. Latest is 3.3.1. This version will end up in future Plone 5.0.x versions.

So you can either wait until Plone 5.0.7 is out, or you add `plone.app.content = 3.3.1` in the `[versions]` section of your `buildout.cfg`.
